import {
  IconBarcode,
  IconChartLine,
  IconCoin,
  IconList,
  IconListDetails,
  IconMoneybag,
  IconSettingsAutomation,
  IconUserCircle,
  IconUsers,
} from "@tabler/icons";

const data = [
  {
    id: 1,
    link: "/",
    label: "statistics.title",
    icon: IconChartLine,
    permission: "statistics.view",
  },
  {
    id: 2,
    link: "/admins",
    label: "admins.title",
    icon: IconUsers,
    permission: "admins.view",
  },
  {
    id: 3,
    link: "/spend",
    label: "spends.title",
    icon: IconUsers,
    permission: "spends.view",
  },
  {
    id: 4,
    link: "/users",
    label: "customers.title",
    icon: IconUserCircle,
    permission: "users.view",
  },
  {
    id: 5,
    link: "/products",
    label: "products.title",
    icon: IconBarcode,
    permission: "products.view",
  },
  {
    id: 6,
    link: "/settings",
    label: "settings.title",
    icon: IconSettingsAutomation,
    permission: "settings.view",
  },
  {
    id: 7,
    link: "/payments",
    label: "payments.title",
    icon: IconMoneybag,
    permission: "payments.view",
  },
  {
    id: 8,
    link: "/roles",
    label: "roles.title",
    icon: IconSettingsAutomation,
    permission: "roles.view",
  },
  {
    id: 9,
    link: "/orders",
    label: "orders.title",
    icon: IconList,
    permission: "orders.view",
  },
  {
    id: 10,
    link: "/kassa",
    label: "kassa.title",
    icon: IconListDetails,
    permission: "kassa.view",
  },
  {
    id: 11,
    link: "/loan",
    label: "loans.title",
    icon: IconCoin,
    permission: "loans.view",
  },
];
export default data;
